Yuanpei-Intelligence/YPPF

app/utils.py, app/views.py, boottest/settings.py, boottest/urls.py
Use @required_login as far as possible
Change authentication method ( md5 to sha256, add time stamp ) for underground app.
by pkuGenuine July.14
=> Auth modification

app/models.py, app/urls.py, app/views.py, app/wechat_send.py, boottest/settings.py, templates/activity_subscribe.html
1. 增加了订阅页面的前端（用户可通过该界面选择订阅组织）
2. 增加了订阅页面相关views.py
3. 增加订阅用户提醒（企业微信相关，未测试）
=> add subscribe function

app/views.py, templates/activity_info.html
Add API for NP to apply/withdraw activity.
Fix bugs in Activity API.
=> Activity_API_2

app/views.py, templates/activity_info.html, templates/orginfo.html
活动详情页的照片展示还没想好具体的交互形式（最多三张？在Models里加三个Imagefield类型字段？），现在是硬编码。
尝试提交活动会出bug，调试发现是applyActivity函数里【可以读取willingness但会抛出异常】，没有测出具体是哪句...
=> 新增活动详情页+更新组织页

app/utils.py, app/views.py, templates/stuinfo.html
=> fix stuinfo on phone

app/data_import.py, app/urls.py
增加了导入活动部分（简单）
数据部分只做了3组18个，有需要可以后续添加
=> load activity

app/utils.py, app/views.py, templates/comment.html, templates/organization_add.html, templates/organization_audit.html, templates/reimbursement_add.html, templates/reimbursement_comment.html
issue147,顺带加上申请理由30行改为3行
评论整合为comment.html，以后只需要include进来即可，增加 addcomment函数
为了不耽误进度，就先实现了以上功能。
至于“申请中的新建组织or新建报销的呈现”的实现则今晚再PR上去
=> 新建组织信息为空的issue+评论整合为一个html+新增评论api

app/views.py, templates/stuinfo.html
=> fix stuinfo

app/utils.py, templates/base.html, templates/notifications.html, templates/person_account_setting.html, templates/stuinfo.html, templates/welcome_page.html
=> fix wrapped email(or)

templates/index.html
=> resolve uncovered index image

app/views.py, templates/activity_add.html, templates/activity_info.html
=> Activity inner

templates/neworganization_show.html, templates/welcome_page.html
=> constrain activity caption height

app/activity_utils.py, templates/user_agreement.html
改了一下用户须知页面的展示，我觉得还行，你要觉得不好看再自己调一下吧
=> User agreement Front End

app/models.py, app/reimbursement_utils.py, app/views.py, templates/activity_add.html, templates/modify_reimbursement.html
(1)活动结项增加自由选择老师逻辑 ;
(2)修复隐藏小组时职位出现数字的bug.
=> 活动结项增加自由选择老师逻辑

app/views.py
=> 个人主页‘相同组织’按钮

app/scheduler_func.py, app/urls.py, app/utils.py, app/views.py, templates/org_left_navbar.html, templates/user_left_navbar.html
Bug fix:
Update the notification status when the recorded activity proceed to PROGRESSING
UE Improvement:
Account shifting
=> Activity dev

app/models.py, app/notification_utils.py, app/scheduler_func.py, app/utils.py
=> 避免 remind activity 执行两次

app/views.py, templates/stuinfo.html
看别人的时候根据是否展示性别在姓名后面加性别符号
看自己的时候总是显示，但若不公开性别则灰色
=> add gender display

app/views.py
=> fix same activity

app/activity_utils.py, app/models.py, app/scheduler_func.py, app/utils.py, app/views.py, templates/activity_add.html, templates/activity_show.html
BonusPoint roll back when activity is canceled.
Use past activity as template to create new one ( no full-in for time and pictures ).
=> New features:

app/scheduler_func.py
=> Update lagging activities

app/data_import.py, app/urls.py, app/views.py
=> 解决组织类型导入的bug && 顺手发现的代码重构之后的一点点小bug

.gitignore, app/admin.py, app/models.py
1、增加LaunchCourse模型和其他附属模型
2、在admin页面中显示课程发布信息
3、修改.gitignore，不提交课程的宣传图片
=> 新增Course模型，记录课程发布的相关信息

app/models.py
新增cur_week 和end_week 连个字段，end_week代表总周数
=> Coursetime新增字段

app/course_views.py, templates/lesson_add.html
=> 修改课程活动页面显示“长期课程活动”提示

app/course_utils.py, templates/activity_info.html, templates/course_info.html, templates/select_course.html
=> 选课页面和课程详情页面美化

app/course_views.py
创建单次活动成功后跳转聚合页面（原来是跳转到修改该活动的页面） @qingzhenduyu
=> 创建单次活动成功后跳转聚合页面

templates/feedback_welcome.html
本来想摆烂了，没想到我的聪明才智把它改出来了。。自我感动。。
=> 把按钮修改为icon

app/course_utils.py, app/course_views.py, app/scheduler_func.py
补退选开始以后才可以 临时新增课时
临时新增的课时的发起的活动为  set(当前选课人+当前课程小组人)
=> 增加临时新增课时的时间判断

app/data_import.py, local_json_template.json
=> 修改导入是对表格数据的判断，添加导入时对是否有效字段的编辑

Appointment/utils/scheduler_func.py, Appointment/utils/web_func.py, app/YQPoint_views.py, app/course_utils.py, app/scheduler_func.py, app/views.py
Modify YQPoint transfer backend. Add a decorator to functions requiring scheduler.
=> Modify YQPoint transfer backend. Add a decorator to functions

templates/welcome_page.html
=> 不显示空白的活动介绍

app/data_import.py, app/urls.py
将data_import.py中各个load函数的执行部分抽离出来，新建单独的视图函数进行权限检查并调用执行函数。
视图函数的名称与原来的load函数名称有所出入，在urls.py中作了相应修改。
=> data_import.py中的函数分离

app/data_export.py
data_export.py 组织数据导出：导出组织的活动，以及每人参加组织的情况
=> data_export.py 组织数据导出：导出组织的活动，以及每人参加组织的情况

app/course_utils.py, app/course_views.py
course_utils.py: create_single_course_activity, modify_course_activity, cancel_course_activity, course_activity_base_check, check_ac_time_course
course_views.py: editCourseActivity, addSingleCourseActivity
=> 为单次课程活动相关函数添加注释

templates/Appointment/admin-index.html, templates/Appointment/booking.html, templates/Appointment/checkout.html
1. 在组织账户页面添加长期预约条目展示和长期预约入口
桌面/平板/手机
2. 预约数量已达上限时禁用长期预约入口
桌面/平板/手机
3. 为可续约的长期预约条目添加续约入口
桌面/平板/手机
4. 为组织账户的时间选择页面添加切换预约类型功能
桌面/平板/手机
5. 为所有用户添加房间切换功能
桌面/平板/手机
6. 为组织账户预约确认页面添加筛选小组成员和导入小组成员入口
桌面/平板/手机
7. 为组织账户预约确认页面添加长期预约相关表单字段
桌面/平板/手机
=> 添加前端页面的长期预约功能

Appointment/__init__.py, Appointment/admin.py, Appointment/models.py, Appointment/urls.py, Appointment/utils/scheduler_func.py, Appointment/utils/utils.py, Appointment/utils/web_func.py, Appointment/views.py, app/utils.py, templates/Appointment/admin-index.html, templates/Appointment/booking.html, templates/Appointment/checkout.html, templates/org_left_navbar.html
长期预约展示信息补充，审核状态变更微信通知，续约和取消长期预约
=> Longterm appointment review

Appointment/views.py, templates/Appointment/admin-index.html, templates/Appointment/booking.html
=> 更新长期预约的条目展示ui，修改预约时间选择提示

Appointment/utils/web_func.py, Appointment/views.py
在web_func.py里实现了appointment2Display函数，把单次预约的有关信息填入供前端展示的词典
=> task33_把填写appoint_info的工作整理为函数appointment2Display

templates/yp_library/search.html, templates/yp_library/welcome.html
=> 搜索结果前端显示，已嵌入搜索框

app/course_utils.py, app/course_views.py, app/models.py, app/scheduler_func.py, templates/lesson_add.html, templates/org_show_course_activity.html, templates/register_course.html
学期初发起课程新增字段
单次课程活动新增字段
课程显示页面新增状态和信息
=> 添加书院课程发布和修改环节

app/course_views.py, app/org_views.py, app/views.py, templates/course_record.html, templates/org_show_course_activity.html, templates/orginfo.html
=> 课程管理界面增加发送通知+手工签到完成后跳转

app/activity_views.py, app/models.py, templates/activity_summary_show.html, templates/modify_activity_summary.html
=> 修改PR #672 细节

app/academic_utils.py
=> 学术地图编辑界面小bug修改

app/urls.py, app/views.py, templates/index.html, utils/views.py
=> 将函数视图转为类视图

.devcontainer/docker-compose.yml, achievement/admin.py, achievement/apps.py, achievement/models.py, achievement/tests.py, achievement/urls.py, achievement/views.py, boot/settings.py, boot/urls.py, templates/achievement/view_achievements.html
Only Model created now. Event and handler not set, front end is way too plain
=> Achievement init

.github/workflows/basetest.yml, scripts/init_migrations.sh
fix a bug in test framework
add sleep delay and makemigrations command
=> fix a bug in test framework

achievement/API.py, achievement/api.py, achievement/models.py
想请问下这两个接口所需的输入输出是这个意思么～ 以及也想问下若出现异常中途返回应该怎样处理（像这样可以吗～）感谢！
=> 添加了处理触发成就和批量添加成就的接口

app/config.py, app/course_utils.py, app/course_views.py, app/jobs.py, app/org_utils.py, boot/settings.py, dm/load_funcs.py, dormitory/management/commands/create_dormitory_questionnaire.py, dormitory/views.py, generic/admin.py, generic/jobs.py, generic/views.py, questionnaire/views.py, scheduler/adder.py, scheduler/scheduler.py, templates/Appointment/index.html, templates/course_info.html, templates/dormitory/dormitory_routine_QA.html, templates/help.html, templates/showPools.html
Draft: Add changes from production env.
=> sync_server_change

app/activity_utils.py, app/activity_views.py, app/jobs.py, boot/test/test_query.py, generic/models.py, templates/activity/finished_center.html, templates/activity/summary_application.html, templates/activity/weekly_summary.html, utils/models/query.py
- 进入修改活动总结界面时自动填充原有的参与人
- 根据修改的参与人员进行元气值补发放与撤销发放
=> 为活动总结修改界面添加修改参与人员的接口

Appointment/views.py, app/YQPoint_utils.py, app/YQPoint_views.py, app/utils.py, templates/showPools.html
在元气值兑换、预约地下室时，增加了发起人需要是活跃用户的限制。
在`app/utils.py`增加了一个检查是否是活跃用户的decorator.
=> 增加元气值兑换和预约地下室活跃用户检查

static/Appointment/assets/css/summary2023.css, templates/Appointment/summary2023.html
=> 2023年度总结-patch2

app/admin.py, app/views.py, scripts/generate_testdata.py
修改了subscibeOrganization页面的查询语句
修复了admin小组页面`订阅全部`和`取消订阅全部`的bug
添加了生成大量测试数据的脚本
=> 优化小组一览界面的加载速度，添加批量生成数据的脚本

Appointment/appoint/manage.py
=> 修改URL可以预约非法时间 #656

feedback/views.py
如果已经删除（DELETED）了反馈或者未填写过反馈，新建反馈
如果填写过且未删除（DRAFTED、ISSUED），修改现有反馈
=> #685 删除反馈再次申诉会打开删除的反馈

app/course_utils.py
将选课成员的来源从选课系统改为了组织成员，避免手动选课无法加入的问题
=> 修复书院课导出名单的问题 (#653)

templates/Appointment/summary2024.html
develop里面有错别字，但是develop是protected branch，所以开一个新的PR来修改
=> Fix conflicts for PR #896

app/course_utils.py
=> 手动更新学时表bug修复
