Yuanpei-Intelligence/YPPF

- app/views.py
- app/wechat_send.py
1.默认多线程定时任务，不堵塞（但仍可能修改设置）
2.解耦创建单个通知与单个发送到微信的逻辑（之后的批量创建和发送时会有相关）
3.增加容错，用于将错误的相对路径转化为绝对路径
4.新增notification发送者或接受者为组织时的逻辑
5.限制单次发送量，并加入json设置中
6.新增可选local_json项，路径：`config/wechat_send/[receivers,blacklist,use_scheduler]`，`thresholds/[wechat_budget, activity_budget]`
> 修改所有发送到微信的api

- app/course_views.py
- templates/org_show_course_activity.html
更新后，聚合页面效果如图所示：
P.S. 考虑到按钮组难扩展、易溢出，一番调试后我还是考虑保留了下拉菜单。
聚合页面中，已链接“增加课时”，（未开始课程活动）“修改活动”。
> 更新聚合页面前端并添加链接

- app/course_utils.py
- app/course_views.py
- app/models.py
- templates/course_record.html
- templates/lesson_add.html
- templates/org_show_course_activity.html
- templates/register_course.html
- templates/user_left_navbar.html
实现逻辑：
（1）课程小组非小组成员、老师和负责人（书院辅导员）均无法计入学时；
（2）每次刷新学时呈现页面，更新参与次数，避免出现助教手动调整签到或者未结束课程活动结束后导致参与次数的修改无法在学时表中呈现出来；
（3）增加结束课程按钮（前提是所有课程活动均结束！）：
功能如下：a）取消每周定时发布活动的逻辑；b)创建学时表（注意去重）；c）通知选课同学，该课程已结束。
> 修复学时部分bug&增加结束课程逻辑

- app/course_views.py
- templates/course_record.html
现在的实现不需要在服务器上储存excel文件，而是直接下载到用户浏览器里
已实现在文件名中加入中文
> 导出学时记录为表格 （前端+后端）

- templates/orginfo.html
- templates/select_course.html
- templates/stuinfo.html
“在个人主页的【我的小组】下面增加【历史小组】，【我的活动】增加一个【历史活动】，组织主页的我的活动增加【历史活动】，然后filter的函数pht已经帮写好了，就相当于加一个呈现block”
（没找到Pht的PR，可以搜索关键词“后端对接”找到对应的暂时的前端变量名）
“1、比例没有调整 2、提示语放在表格里有点奇怪 3、补退选不用badge算了，对不齐”改好了
> 组织和个人的历史活动/历史组织&选课页的三个bug

- yp_library/test/test_lendinfo.py
- yp_library/utils.py
- yp_library/views.py
1. yp_library/utils.py：工具函数
（1）get_my_records：根据reader_id查询给定读者的借阅记录，可根据returned参数限定图书归还状态（可为空），根据status参数限定借阅记录状态（可谓空）。
（2）get_lendinfo_by_readers：根据readers（同一user）查询未归还记录和已归还记录，对于readers中的每个reader通过调用get_my_records函数实现借阅记录查询
2. yp_library/views.py：借阅信息页面，通过调用yp_library/utils.py中的get_lendinfo_by_readers函数获取分别表示未归还记录和已归还记录的两个列表，并放入frontend_dict
3. yp_library/test/test_lendinfo.py：对utils.py的get_my_records和get_lendinfo_by_readers函数进行了简单的测试，其中，由于get_my_records函数对于未归还记录的记录类型判断受测试时的时间影响，已经注释掉了
> task24_借阅信息页面的后端数据准备

- app/feedback_views.py
- templates/Appointment/admin-credit.html
- templates/Appointment/admin-index.html
- templates/org_left_navbar.html
- templates/yp_library/lendinfo.html
- yp_library/admin.py
- yp_library/models.py
- yp_library/test/test_lendinfo.py
- yp_library/utils.py
这个pr的主要更改是实现书房借阅信息界面，但同时也完成了一些杂项任务：
1. 去除小组信息界面侧边栏的问答中心入口；
2. 注册元培书房admin权限；
3. 略微修改借阅信息界面后端逻辑，方便前端利用。
4. 针对借阅信息界面后端逻辑的修改，略微修改了test文件。
书房借阅信息界面的具体信息：
1. 进行中的借阅记录以表格形式呈现，按照归还截止时间正序排列（越靠前的记录应归还时间越早）。呈现字段有：书名（前端加上书名号）、借阅时间、归还截止时间、状态。状态分一般记录（距离归还截止时间大于1天的）、接近期限（未逾期但距离归还截止时间不到1天）、已逾期，使用badge形式，详见下方截图。
2. 已完成的借阅记录同样以表格形式呈现，按照归还时间逆序排列（越靠前的记录归还时间越晚/与现在越接近）。呈现字段有：书名（前端加上书名号）、借阅时间、归还截止时间、归还时间、申诉状态。申诉状态分无需申诉（未逾期的记录，直接用文字呈现）、申诉（未申诉的逾期记录允许申诉，用button呈现，后期可链接到申诉界面）、申诉中、申诉通过、申诉不通过（用badge呈现）。特别地，若一条已完成的借阅记录为逾期记录，“归还时间”将变为较为醒目的红色。
> 上面提到已完成借阅记录中未申诉的逾期记录会呈现“申诉”button，但申诉的逻辑还未完成，所以这个button暂时还未链接到任何的url，可以待后续申诉逻辑完成后再完善。
效果图：
（1）电脑端：
（2）手机端
> 一些杂项任务 + 书房借阅信息界面前端

- yp_library/test/test_lendinfo.py
- yp_library/test/test_search.py
- yp_library/utils.py
- yp_library/views.py
1.search_books的参数改为**query_dict，get_query_dict获取的query_dict不保留post_dict中不存在的键；全关键词检索的搜索范围固定为identity_code/title/author/publisher，query_dict中keywords项仅保留关键词而不再是一个列表
2.参数、返回值类型的QuerySet补充为QuerySet[Model]
3.判定账号类型时使用UTYPE_PER
4.对search、lendinfo的测试函数进行拆分，search的测试函数根据search_books的修改进行了调整
> 书房后端的一些小改动

- app/academic_utils.py
- app/academic_views.py
- app/models.py
- app/test/test_search_academic.py
- app/urls.py
- app/views.py
- boottest/settings.py
- templates/search_academic.html
总体工作：新建academic_utils.py与academic_views.py，写好学术地图搜索结果页面后端，添加对应的html文件与url。
具体：目前只支持全关键词搜索，根据关键词筛选所有content中含有关键词的条目（entry），并根据人进行归纳（即将一个人的所有content含关键词的entry整合成一个字典），最后提供给前端一个含有搜索结果字典（key还包含姓名与年级）的list。
> 学术地图搜索结果页面后端

- app/views.py
- templates/orginfo.html
暂时未实现跳转之后的定位，考虑到可能一个小组对应多个课程，能否在另作一个页面与小组信息、成员档案等并列，类似于一个新的聚合页面展示组织对应的所有选课？
> 小组主页增加跳转选课的按钮

- app/academic_utils.py
- app/chat_api.py
- app/chat_utils.py
- app/models.py
- app/views.py
- templates/showChats.html
- templates/stuinfo.html
- templates/viewChat.html
1.academic_utils.py的comments2Display函数补充前端量"anonymous_chat"，"accept_anonymous"；在问答中心页面通过这两个量判断能否匿名创建问答/能否匿名追问，如不能，相应的checkbox或textarea变为disabled并给出提示语；问答详情页面类似
示意图如下：
（红字是鼠标悬浮在“匿名提问”或checkbox上时出现的）
2.问答中心、个人主页这两个页面都设置了刷新后打开刷新前所在tab的功能，原来两个页面在sessionStorage中记录tab信息时用的变量名是相同的，从而load一个界面时采用的可能是另一个界面unload前记录的tab信息，导致出现问题。目前两边使用不同的变量名，应该没问题了。
> 优化禁止匿名问答的显示方法

- Appointment/admin.py
- Appointment/models.py
- Appointment/utils/scheduler_func.py
- Appointment/utils/web_func.py
- Appointment/views.py
- 创建预约时的所需人数逻辑更加清楚，将所需人数记入预约中
- 摄像头检查时不再当场计算，而是使用记录的所需人数
- 临时预约flag全面转化为type判断
> 移除临时预约flag，使用记录数据

- app/academic_utils.py
- app/academic_views.py
- app/test/test_audit_academic.py
- app/urls.py
- templates/audit_academic.html
- templates/stuinfo.html
- templates/user_left_navbar.html
academic_views.py新增auditAcademic，首先检查身份为教师，随后调用academic_utils.py的get_wait_audit_student获取所有有待审核的AcademicTagEntry/AcademicTextEntry的NaturalPerson集合；urls.py增加/auditAcademic/
非教师身份进入会跳转回首页并显示“只有教师账号可进入学术地图审核页面!”
新增audit_academic.html，如下图
点击姓名或右侧按钮均可跳转到其个人主页并打开学术地图tab
另外还顺便对stuinfo.html做了一点点优化，原来进入主页后会读取url中的tab=xxx、打开对应tab、修改window.location.href以删除url中的tab=xxx，而修改window.location.href会导致页面刷新，因而可能看到页面在“个人信息”tab和“学术地图”tab之间反复横跳两次；现在改为用window.history.replaceState修改url，不会自动刷新，避免了上述问题。
现在在网页测试审核页面不太方便，我写了一个test简单验证了一下工具函数get_wait_audit_student的输出
> 学术地图审核页面前后端

- app/academic_views.py
- app/views.py
- templates/stuinfo.html
- templates/user_left_navbar.html
1.stuinfo.html提问按钮获取传user.id处把person.id改为person.person_id.id
2.academic_views.py的applyAuditAcademic函数HttpRequest.user改为request.user
3.academic_views.py和views.py的检查teacher前补充检查用户类型为person
4.增设学生个人账号学术地图侧边栏，两个下拉条目分别跳转stuinfo的academic_map tab和AcademicQA
5.美化了一下stuinfo的academic_map tab前端
> 修改学术地图相关的若干bug

- templates/user_left_navbar.html
原来直接复制了下面的一段代码，忘记改collapse submenu的id和menu的href了，目前已修改
> 修复学术地图侧边栏bug

- app/YQPoint_utils.py
- app/YQPoint_views.py
- app/constants.py
- app/models.py
- boottest/__init__.py
- local_json_template.json
- templates/myPrize.html
- templates/showPools.html
1.每个奖池中的奖品按剩余数量降序排序，已卖完的在最后，例如
2.奖池页面更名为“元气值商城”，和其他地方保持一致
3.一些零碎修改，如constants.py中YQP_PER_HOUR的default设为10，几个奖品相关的模型加str属性
4.我的奖品和元气值商城页面前端导入help.html。目前与元气值相关的三个页面均有“使用帮助”，如下图
另外，这三处帮助信息也已导入后台数据库
*元气值文档中还有一句比较概括性的“_元气值是YPPF的交易系统，用于奖励活跃用户。个人用户可通过签到、活动参与、公开反馈等方式获取元气值，并可在元气值商城兑换奖品。_”这句话需要加进去吗？该放在哪里呢？
*原定要给兑换奖池加上总的可兑换次数，但是感觉不是很有必要，因为每个奖品都有标注剩余数量、点开详情也能看到用户自己的剩余可兑换次数，把这些加起来对用户而言应该意义不大
> 与元气值后端相关的一些优化

- app/YQPoint_utils.py
- app/models.py
- generic/models.py
1. 抽到空盲盒时，对用户进行元气值补偿（在设定好的下限到上限的闭区间内随机抽取），并返回相应的提示
2. 将元气值补偿的上限和下限（整型）添加到奖池属性中
3. 添加了”奖池补偿“作为新的元气值来源
4. 将是否为空盒（布尔型）添加到奖池奖品的属性中
> 实现了空盲盒元气值补偿功能

- app/admin.py
- dormitory/admin.py
- feedback/admin.py
发现竟然是历史遗留问题。似乎是写的时候把 `ForeignKey` 当做搜索条件，但是没有注意到 `ForeignKey` 上并不能直接调用 `icontains`，所以指定用各个 `ForeignKey` 的 `name` 作为搜索条件，解决了这个问题。
顺便把一些搜索放到筛选里面去了，因为只有有限的几个值，似乎筛选更加合理。
Before:
After:
> 修了一下在某些管理界面搜索时出现的500错误

- app/course_views.py
- app/org_views.py
- app/utils.py
- templates/user_left_navbar.html
元气值商城、地下室预约中不允许已毕业用户使用的问题已在PR #806 中实现。
这个 PR 中加入了书院课退课、选课按钮，小组状态更改（现在似乎只有新建小组？）时检查用户是否已经毕业，如果已经毕业，会在页面上方显示一条错误信息，如下图所示：
> 在书院课退选课、小组状态更改界面检查用户是否激活

- dormitory/admin.py
- dormitory/management/commands/create_dormitory_questionnaire_2023.py
- dormitory/management/commands/create_dormitory_questionnaire_2024.py
- dormitory/views.py
执行修改后的create_questionnaire脚本之后，不同年份的问卷的标题会有所不同，如下所示：
同时，在 生活习惯调研 问卷界面会根据`next_semester().year`来选择合适的问卷。
> 在生活习惯调研后面加上年份以示区别；问卷页面用next_semester确定应该显示哪一份问卷

- app/YQPoint_utils.py
- app/admin.py
Sets the end time to now and invokes run_lottery on all lottery pools that's selected.
> 奖池管理界面“立即停止”功能

- dm/management/commands/autograduate.py
为完成今年调整权限的工作，添加了批量毕业指定年级学生的脚本，并防止了误伤教师，延迟毕业的学生还需通过管理站点手动调整回来
> 添加了批量毕业指定年级学生的脚本

- templates/orginfo.html
通过修改padding-top与padding-left，使得标签被鼠标滑过或被触屏点击时向上移动的动画不再会被遮挡
> 修改了小组信息的标签对应的padding，使其动画效果不再被遮挡

- Appointment/appoint/manage.py
- Appointment/config.py
- Appointment/utils/utils.py
- Appointment/views.py
- app/admin.py
- app/views.py
- scripts/generate_testdata.py
- templates/Appointment/booking.html
#866 添加对单日预约时长和同时段预约的限制，修改前端的提示信息
配置文件 `Appointment/config.py`
```python
max_appoint_time = timedelta(hours=6)
allow_overlap = False
```
> #866 添加对单日预约时长和同时段预约的限制，修改前端的提示信息

- app/course_utils.py
把对应的`NaturalPerson`用`select_for_update()`锁起来，就可以避免在检查合法性和创建选课记录两个操作不原子导致的并发问题。
修改 `CourseParticipation` 的那个transaction没有去掉，因为[Django文档](https://docs.djangoproject.com/en/5.0/topics/db/transactions/#controlling-transactions-explicitly)说不应该在transaction里try/except，而应该放在`with transaction.atomic()`的外面，即使要引入一个新的transaction.
> Fix race condition in registration_status_change

- Appointment/views.py
之前没有排序，所以在最上面的是最早创建的长期预约。让最近创建的在最上面更加方便。
> 我的预约界面长期预约排序
